jobs:
  build:  
    docker:
      - image: cimg/node:14.17.1

    working_directory: backend/addLink

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - dependencies-cache-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - dependencies-cache

      - run:
          name: Install Serverless CLI and dependencies
          command: |
            sudo npm i -g serverless
            cd badkenc/addLink
            npm install


      - run:
          name: Deploy application
          command: sls deploy
          
      - save_cache:
          paths:
            - node_modules
          key: dependencies-cache-{{ checksum "package.json" }}
