name: CI/CD
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '24'
        cache: 'yarn'
        cache-dependency-path: website/yarn.lock
    - name: Enable Corepack
      run: corepack enable
    - name: Build static site
      run: cd website && yarn install && yarn build && yarn generate

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '24'
        cache: 'yarn'
        cache-dependency-path: website/yarn.lock
    - name: Enable Corepack
      run: corepack enable
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1
    - name: Create env file for website
      run: |
        touch .env
        echo TIL_API_HOST =${{ secrets.TIL_API_HOST }} >> ./website/.env
    - name: Build static site
      run: cd website && yarn install && yarn build && yarn generate
    - name: Deploy static site to S3 bucket
      run: aws s3 sync ./website/.output/public/ s3://todayilearned-prod --delete
