name: CI/CD
on:
  push:
    branches:
      -  master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1
    - name: Create env file for website
      run: |
        touch .env
        echo TIL_API_HOST =${{ secrets.TIL_API_HOST }} >> ./website/.env
    - name: Build static site
      run: cd website && yarn install && yarn build && yarn generate
    - name: Deploy static site to S3 bucket
      run: aws s3 sync ./website/dist/ s3://todayilearned-prod --delete
